[2023-11-05T16:15:53.703+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customers.create_customers_table manual__2023-11-05T16:15:51.316958+00:00 [queued]>
[2023-11-05T16:15:53.719+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customers.create_customers_table manual__2023-11-05T16:15:51.316958+00:00 [queued]>
[2023-11-05T16:15:53.720+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-05T16:15:53.721+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-11-05T16:15:53.721+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-05T16:15:53.742+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_customers_table> on 2023-11-05 16:15:51.316958+00:00
[2023-11-05T16:15:53.749+0000] {standard_task_runner.py:55} INFO - Started process 17427 to run task
[2023-11-05T16:15:53.754+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customers', 'create_customers_table', 'manual__2023-11-05T16:15:51.316958+00:00', '--job-id', '463', '--raw', '--subdir', 'DAGS_FOLDER/customers.py', '--cfg-path', '/tmp/tmp53z16f73']
[2023-11-05T16:15:53.757+0000] {standard_task_runner.py:83} INFO - Job 463: Subtask create_customers_table
[2023-11-05T16:15:53.838+0000] {task_command.py:376} INFO - Running <TaskInstance: customers.create_customers_table manual__2023-11-05T16:15:51.316958+00:00 [running]> on host 9d85c6014d6e
[2023-11-05T16:15:54.128+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customers
AIRFLOW_CTX_TASK_ID=create_customers_table
AIRFLOW_CTX_EXECUTION_DATE=2023-11-05T16:15:51.316958+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-05T16:15:51.316958+00:00
[2023-11-05T16:15:54.140+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-05T16:15:54.145+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS customers (
            Index INT NOT NULL primary key,
            Customer_Id varchar(100),
            First_Name varchar(100),
            Last_Name varchar(100),
            Company varchar(100),
            City varchar(100),
            Country varchar(100),
            Phone_1 varchar(100),
            Phone_2 varchar(100),
            Email varchar(100),
            Subscription Date,
            Website varchar(100)
        );
    , parameters: None
[2023-11-05T16:15:54.146+0000] {postgres.py:96} INFO - NOTICE:  relation "customers" already exists, skipping

[2023-11-05T16:15:54.160+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=customers, task_id=create_customers_table, execution_date=20231105T161551, start_date=20231105T161553, end_date=20231105T161554
[2023-11-05T16:15:54.205+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-05T16:15:54.240+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
