[2023-11-08T07:46:51.694+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:46:51.711+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:46:51.712+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T07:46:51.713+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-11-08T07:46:51.713+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T07:46:51.734+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): save_customers_to_excel> on 2023-11-07 00:00:00+00:00
[2023-11-08T07:46:51.742+0000] {standard_task_runner.py:55} INFO - Started process 101 to run task
[2023-11-08T07:46:51.746+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customers', 'save_customers_to_excel', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '599', '--raw', '--subdir', 'DAGS_FOLDER/customer_1.py', '--cfg-path', '/tmp/tmpmfsao4zi']
[2023-11-08T07:46:51.748+0000] {standard_task_runner.py:83} INFO - Job 599: Subtask save_customers_to_excel
[2023-11-08T07:46:51.842+0000] {task_command.py:376} INFO - Running <TaskInstance: customers.save_customers_to_excel scheduled__2023-11-07T00:00:00+00:00 [running]> on host 294bdf3ccac4
[2023-11-08T07:46:52.126+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customers
AIRFLOW_CTX_TASK_ID=save_customers_to_excel
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-07T00:00:00+00:00
[2023-11-08T07:46:52.137+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-08T07:46:52.263+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-08T07:46:52.391+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-08T07:46:52.404+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=customers, task_id=save_customers_to_excel, execution_date=20231107T000000, start_date=20231108T074651, end_date=20231108T074652
[2023-11-08T07:46:52.450+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-08T07:46:52.476+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-08T13:06:44.717+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T13:06:44.740+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T13:06:44.741+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T13:06:44.747+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-11-08T13:06:44.749+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T13:06:44.793+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): save_customers_to_excel> on 2023-11-07 00:00:00+00:00
[2023-11-08T13:06:44.809+0000] {standard_task_runner.py:55} INFO - Started process 198 to run task
[2023-11-08T13:06:44.815+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customers', 'save_customers_to_excel', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/customer_1.py', '--cfg-path', '/tmp/tmpoe8jssul']
[2023-11-08T13:06:44.825+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask save_customers_to_excel
[2023-11-08T13:06:45.060+0000] {task_command.py:389} INFO - Running <TaskInstance: customers.save_customers_to_excel scheduled__2023-11-07T00:00:00+00:00 [running]> on host 6287529917c2
[2023-11-08T13:06:45.308+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customers
AIRFLOW_CTX_TASK_ID=save_customers_to_excel
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-07T00:00:00+00:00
[2023-11-08T13:06:45.354+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-11-08T13:06:45.847+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-11-08T13:06:45.971+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-08T13:06:45.990+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customers, task_id=save_customers_to_excel, execution_date=20231107T000000, start_date=20231108T130644, end_date=20231108T130645
[2023-11-08T13:06:46.086+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-11-08T13:06:46.124+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
